# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GitHub\HEI_fafg\code\dialog_create_group.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 251)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 11, 521, 230))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_group_members = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_group_members.setFont(font)
        self.label_group_members.setObjectName("label_group_members")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_group_members)
        self.lineEdit_group_members = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_group_members.setFont(font)
        self.lineEdit_group_members.setObjectName("lineEdit_group_members")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_group_members)
        self.lineEdit_job_detail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_job_detail.setFont(font)
        self.lineEdit_job_detail.setObjectName("lineEdit_job_detail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_job_detail)
        self.label_job_detail = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_job_detail.setFont(font)
        self.label_job_detail.setObjectName("label_job_detail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_job_detail)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_destination = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_destination.setFont(font)
        self.label_destination.setObjectName("label_destination")
        self.gridLayout.addWidget(self.label_destination, 0, 0, 1, 1)
        self.lineEdit_destination = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_destination.setFont(font)
        self.lineEdit_destination.setObjectName("lineEdit_destination")
        self.gridLayout.addWidget(self.lineEdit_destination, 0, 1, 1, 1)
        self.label_inviter = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_inviter.setFont(font)
        self.label_inviter.setObjectName("label_inviter")
        self.gridLayout.addWidget(self.label_inviter, 0, 2, 1, 1)
        self.lineEdit_inviter = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_inviter.setFont(font)
        self.lineEdit_inviter.setObjectName("lineEdit_inviter")
        self.gridLayout.addWidget(self.lineEdit_inviter, 0, 3, 1, 1)
        self.label_departure_date = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_departure_date.setFont(font)
        self.label_departure_date.setObjectName("label_departure_date")
        self.gridLayout.addWidget(self.label_departure_date, 1, 0, 1, 1)
        self.dateEdit_departure_date = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.dateEdit_departure_date.setFont(font)
        self.dateEdit_departure_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_departure_date.setObjectName("dateEdit_departure_date")
        self.gridLayout.addWidget(self.dateEdit_departure_date, 1, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 1, 2, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_time.setFont(font)
        self.lineEdit_time.setText("")
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tour_rountine = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_tour_rountine.setFont(font)
        self.label_tour_rountine.setObjectName("label_tour_rountine")
        self.horizontalLayout_2.addWidget(self.label_tour_rountine)
        self.lineEdit_tour_rountine = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_tour_rountine.setFont(font)
        self.lineEdit_tour_rountine.setObjectName("lineEdit_tour_rountine")
        self.horizontalLayout_2.addWidget(self.lineEdit_tour_rountine)
        self.checkBox_tour_rountine = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_tour_rountine.setFont(font)
        self.checkBox_tour_rountine.setChecked(True)
        self.checkBox_tour_rountine.setObjectName("checkBox_tour_rountine")
        self.horizontalLayout_2.addWidget(self.checkBox_tour_rountine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_needed_doc = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_needed_doc.setFont(font)
        self.label_needed_doc.setObjectName("label_needed_doc")
        self.horizontalLayout_3.addWidget(self.label_needed_doc)
        self.checkBox_he_permission = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_he_permission.setFont(font)
        self.checkBox_he_permission.setAcceptDrops(False)
        self.checkBox_he_permission.setChecked(True)
        self.checkBox_he_permission.setObjectName("checkBox_he_permission")
        self.horizontalLayout_3.addWidget(self.checkBox_he_permission)
        self.checkBox_customs_pass = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_customs_pass.setFont(font)
        self.checkBox_customs_pass.setAcceptDrops(False)
        self.checkBox_customs_pass.setObjectName("checkBox_customs_pass")
        self.horizontalLayout_3.addWidget(self.checkBox_customs_pass)
        self.checkBox_passport = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_passport.setFont(font)
        self.checkBox_passport.setAcceptDrops(False)
        self.checkBox_passport.setObjectName("checkBox_passport")
        self.horizontalLayout_3.addWidget(self.checkBox_passport)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_special_note = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_special_note.setFont(font)
        self.checkBox_special_note.setObjectName("checkBox_special_note")
        self.horizontalLayout.addWidget(self.checkBox_special_note)
        self.label_special_note = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_special_note.setFont(font)
        self.label_special_note.setObjectName("label_special_note")
        self.horizontalLayout.addWidget(self.label_special_note)
        self.lineEdit_special_note = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_special_note.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_special_note.setFont(font)
        self.lineEdit_special_note.setObjectName("lineEdit_special_note")
        self.horizontalLayout.addWidget(self.lineEdit_special_note)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.clicked['QAbstractButton*'].connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_group_members, self.lineEdit_job_detail)
        Dialog.setTabOrder(self.lineEdit_job_detail, self.lineEdit_destination)
        Dialog.setTabOrder(self.lineEdit_destination, self.lineEdit_inviter)
        Dialog.setTabOrder(self.lineEdit_inviter, self.dateEdit_departure_date)
        Dialog.setTabOrder(self.dateEdit_departure_date, self.lineEdit_time)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "团组信息录入"))
        self.label_group_members.setText(_translate("Dialog", "团组成员"))
        self.label_job_detail.setText(_translate("Dialog", "出访任务"))
        self.label_destination.setText(_translate("Dialog", "目的地"))
        self.lineEdit_destination.setText(_translate("Dialog", "土耳其"))
        self.label_inviter.setText(_translate("Dialog", "邀请单位"))
        self.lineEdit_inviter.setText(_translate("Dialog", "LID公司"))
        self.label_departure_date.setText(_translate("Dialog", "出访时间"))
        self.label_time.setText(_translate("Dialog", "停留时间"))
        self.label_tour_rountine.setText(_translate("Dialog", "出访路线"))
        self.lineEdit_tour_rountine.setText(_translate("Dialog", "哈尔滨"))
        self.checkBox_tour_rountine.setText(_translate("Dialog", "原路返回"))
        self.label_needed_doc.setText(_translate("Dialog", "需办理手续"))
        self.checkBox_he_permission.setText(_translate("Dialog", "批件"))
        self.checkBox_customs_pass.setText(_translate("Dialog", "路条"))
        self.checkBox_passport.setText(_translate("Dialog", "护照"))
        self.checkBox_special_note.setText(_translate("Dialog", "特殊情况"))
        self.label_special_note.setText(_translate("Dialog", "特殊情况说明"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

